# Generated by Django 3.2.9 on 2021-11-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('plant_species', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('min_humidity_level', models.FloatField()),
                ('max_humidity_level', models.FloatField()),
                ('average_lux_amount_per_day', models.FloatField()),
                ('target_temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_humidity', models.FloatField()),
                ('current_lux', models.FloatField()),
                ('current_temperature', models.FloatField()),
                ('owner_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('plant_species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cuppy.requirement')),
            ],
        ),
    ]
