# Generated by Django 3.2.9 on 2021-12-04 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cuppy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTCentralClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MQTTSensorActuatorClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_actuator', models.BooleanField()),
                ('value_file', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=256)),
                ('central_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuppy.mqttcentralclient')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuppy.plant')),
            ],
        ),
    ]
