# Generated by Django 3.2.9 on 2021-12-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuppy', '0002_mqttcentralclient_mqttsensoractuatorclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttsensoractuatorclient',
            name='should_stop_loop',
            field=models.BooleanField(default=True),
        ),
    ]
