# Generated by Django 3.2.9 on 2021-12-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuppy', '0003_mqttsensoractuatorclient_should_stop_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttcentralclient',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuppy.plant'),
            preserve_default=False,
        ),
    ]
