# Generated by Django 3.2.9 on 2021-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuppy', '0004_mqttcentralclient_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttcentralclient',
            name='should_stop',
            field=models.BooleanField(default=True),
        ),
    ]
